[package]
name = "inferno-convert-tiles"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
inferno-tiles = { path = "../inferno-tiles" }
tar = "0.4.43"
