[package]
name = "inferno-tiles"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
bitfield-struct = "0.9.3"
clap = { version = "4.5.23", optional = true }
log = "0.4.22"
rkyv = { version = "0.8.9", features = ["alloc"] }
zerocopy = { version = "0.8.13", features = ["derive"] }
